name: Build Windows Executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Fetch my code

    - name: Set up Flutter
      run: |
        curl -o flutter.zip https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.24.5-stable.zip
        mkdir C:\flutter
        tar -xf flutter.zip -C C:\flutter --strip-components=1
        echo "C:\flutter\bin" >> $env:GITHUB_PATH
        $env:PATH += ";C:\flutter\bin"
        flutter --version

    - name: Install dependencies
      run: flutter pub get

    - name: Build Windows Executable
      run: flutter build windows --release

    - name: Upload Windows Build Artifact
      uses: actions/upload-artifact@v3  # Save the build artifact
      with:
        name: windows-build
        path: build/windows/runner/Release/
